# Generated by Django 4.2.3 on 2023-07-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_compra',
            field=models.DateField(default='2023-07-24'),
            preserve_default=False,
        ),
    ]
